name: Auto Scraper

on:
  push:
    paths:
      - 'input.csv'  # input.csv가 업데이트될 때만 실행

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          NAVER_CLIENT_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_CLIENT_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
        run: python main.py

      - name: Commit and Push results
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          
          # 1. 먼저 바뀐 파일(output.csv)을 등록합니다
          git add output.csv
          
          # 2. 변경사항이 있을 때만 커밋을 진행합니다
          git commit -m "Update search results" || echo "No changes to commit"
          
          # 3. 서버의 최신 내용을 가져와서 합칩니다 (강제성 부여)
          git pull --rebase origin main
          
          # 4. 최종적으로 서버에 올립니다
          git push origin main
